### ISSUE TITLE
Add Splash Screen in Android App

### ISSUE THREAD

**Issue by akarshan96** [Bashmug/HappyPanda#13]
**I'm submitting a ...**  (check one with "x")
- [ ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support requests here, instead ask your query in out Gitter channel ahttps://gitter.im/BashMug/HappyPanda

**Actual Behaviour**

Splash Screen of Android App is not there

**Expected Behaviour**

Splash Screen of Android App should be there

**Steps to reproduce it**

> None

**Related code:**

> None

****Would you like to work on the issue?**

Yes

**Comment by xeon-zolt** [comment]
I think we need to resolve this first #2

**Comment by ItsT-Mo** [comment]
I will take care of the splash screen.

EDIT:
Nevermind, I just saw that @akarshan96 is assigned.

**Comment by akarshan96** [comment]
@ItsT-Mo yeah sure, you can work on it once the logo for the app is decided

**Comment by Sprinting** [comment]
@akarshan96 I'd rather this be done with. The logo should be a simple asset change, after all. A splash screen would make for a good first issue, and there's no sense in delaying because of the logo, just put in one of the candidates. What do you think?

**Comment by Sparker0i** [comment]
I've already made a splash screen.Just in case at #14
