### ISSUE TITLE
Add happy Panda Logo 

### ISSUE THREAD

**Issue by xeon-zolt** [Bashmug/HappyPanda#2]
the logo must be a svg type that can be also used as icon for the app and for different places for the app 
to Know about app check README.md

**Comment by Srijanjha** [comment]
I would like to work on this issue.

**Comment by xeon-zolt** [comment]
@SrijanJha28 Thank you for Volunteering

**Comment by RaiVaibhav** [comment]
I would like to work on this

**Comment by xeon-zolt** [comment]
@RaiVaibhav go ahead we will select the one which suits the purpose best 
ThankYou

**Comment by RaiVaibhav** [comment]
@xeon-zolt added logos [#7](https://github.com/Bashmug/HappyPanda/pull/7)
